### ISSUE TITLE
Switch from pym -> frames library

### ISSUE THREAD

**Issue by mandicai** [texastribune/data-visuals-create#17]
[Basecamp issue](https://3.basecamp.com/3098728/buckets/80634/todos/1652749122)

**Current behavior:** 
We rely on Pym to resize our iframes in response to window height changes, but Pym is not AMP-compatible.

**Desired behavior:** 
Switch to this [`frames` library](https://github.com/rdmurphy/frames) to wrap our embedded graphics in iframes that ARE AMP-compatible 🎉

- [x] Look at the UT polls, which successfully use the `frames` library
- [x] Remove Pym and replace with `frames` code to render graphics
- [x] Create a super simple table/D3 test graphic in the index.html page
- [x] Deploy the test graphic and embed it with the same instructions from the UT polls in a CMS story
- [x] See if it's embedded in an iframe and resizing with height on mobile and across browsers
- [x] Change the printed deploy instructions
- [x] BONUS: Move the CSS snippet to somewhere else other than Ryan's personal GitHub

**Comment by rdmurphy** [comment]
🎊

**Comment by mandicai** [comment]
Lol hi @rdmurphy!!!
