### ISSUE TITLE
Include ad macro in processors.html

### ISSUE THREAD

**Issue by csessig86** [texastribune/data-visuals-create#3]
Right now, if you want to put ads into a feature template using a Google doc, you have manually include the ad macro in macros/processors.html. It'd be nice to have that automatically in there.

Here's an example of how it's done:
https://github.com/texastribune/feature-women-candidates-2018-05/blob/master/app/templates/macros/processors.html

The code that would need to be added:

`{% import 'macros/ads.html' as ads %}`
`{% macro ad(value) %}
  {{ ads.ad(value) }}
{% endmacro %}`

**Comment by mandicai** [comment]
Closed with #23
