### ISSUE TITLE
Improving the ArchieML -> Nunjucks pipeline

### ISSUE THREAD

**Issue by mandicai** [texastribune/data-visuals-create#46]
There are often times when we want to insert a statistic in the text that is pulled from fetched data, or add a function to process text (like formatDate()).

Unfortunately, this doesn't play well with the ArchieML -> Nunjucks templating pipeline. If you add a variable or text inside a function to a Google Doc, ArchieML will just bring that over as the raw text and Nunjucks won't process it.

We currently rely on two options: 1) add the text to the HTML itself (making it hard for editors to edit) or 2) add `<span>` tags in the Google Doc and append formatted text/stats/etc. to the spans on page load.

Neither are ideal, so opening up an issue to explore better ways we can do this.

**Comment by mandicai** [comment]
A solution was implemented in https://github.com/texastribune/feature-tx-coronavirus-tracker-2020-03

**Comment by mandicai** [comment]
```
// render nunjucks variables in the text
  nunjucksEnv.addFilter('renderStringWithNunjucks', str => {
    return nunjucksEnv.renderString(str.toString(), data);
  });
```
(thanks Ryan!)

**Comment by rdmurphy** [comment]
👋 Something we added to our version of this to be more flexible — the ability to pass in your own extra context.

```js
// render nunjucks variables in the text
nunjucksEnv.addFilter('renderStringWithNunjucks', (str, context) => {
  return nunjucksEnv.renderString(str.toString(), {
    ...data,
    ...context
  });
});
```

Helpful if you're making your own variables with `{% set %}` and don't wanna count on your global context always being right. It causes some wacky Nunjucks, tho:

```
{{ val|renderStringWithNunjucks({
  'county': county_data
}) }}
```
